# -*- coding: utf-8 -*-
"""ML_PQRS_Bot_MercadoLibre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GWCQpWDLnSlzJ2a_5J5N1C5owPz1YWF

# 🛒 Asistente Inteligente de PQRS — Mercado Libre
### LangChain · RAG · Random Forest · Telegram Bot ·  SQLite
### Universidad Nacional de Colombia — Sistemas de Información

---

## 📐 Arquitectura General

```
Usuario Telegram
      ↓
Recepción del mensaje (chat_id, username, fecha, texto)
      ↓
Clasificación PQRS  ←── Random Forest + TF-IDF (IA Clásica)
      ↓
Retriever PDF  ←── FAISS Vector Store + PyPDFLoader
      ↓
Recuperación de Contexto Relevante
      ↓
Prompt Template  ←── LangChain PromptTemplate
      ↓
LLM (GPT-4o)
      ↓
Parser de Respuesta
      ↓
Registro en SQLite  ←── pqrs_logs
      ↓
Respuesta Telegram
```

---

**📚 Documentos PDF de Mercado Libre utilizados:**
- `Términos_y_condiciones_Mercado_Libre.pdf`
- `Cómo_devuelvo_un_producto.pdf`
- `Políticas_de_devolución_de_productos.pdf`
- `Compra_protegida_Mercado_Libre.pdf`

**🔑 Secrets de Colab necesarios (panel 🔑 barra lateral):**
- `OPENAI_API_KEY`
- `TELEGRAM_BOT_TOKEN`


---

## 📦 Paso 1 — Instalación de dependencias
"""

# =============================================================================
# PASO 1: Instalar todas las dependencias necesarias
# Se instala el ecosistema LangChain, herramientas RAG y el bot de Telegram
# =============================================================================

# Ecosistema LangChain
!pip install -q \
    "python-telegram-bot>=20.0" \
    "langchain-openai>=1.0" \
    "langchain-community>=0.3" \
    "langchain-core>=0.3" \
    "langchain-text-splitters"

# RAG y procesamiento de PDFs
!pip install -q \
    "pypdf" \
    "faiss-cpu" \
    "tiktoken"

# ML clásico para clasificador PQRS
!pip install -q "scikit-learn>=1.3"

# Visualizaciones académicas
!pip install -q "matplotlib" "seaborn"

# Verificación de versiones instaladas
import importlib.metadata as meta
paquetes = [
    'python-telegram-bot', 'langchain-core', 'langchain-openai',
    'langchain-community', 'faiss-cpu', 'pypdf', 'scikit-learn'
]
print('\n── Versiones instaladas ─────────────────────────────')
for p in paquetes:
    try:
        print(f'  ✅ {p:<30} {meta.version(p)}')
    except meta.PackageNotFoundError:
        print(f'  ❌ {p:<30} no encontrado')

"""## 🔑 Paso 2 — Cargar credenciales desde Colab Secrets"""

# =============================================================================
# PASO 2: Cargar API keys desde Colab Secrets (panel 🔑 barra lateral)
# .strip() elimina \r\n ocultos que rompen las peticiones HTTP
# NUNCA escribir las claves directamente en el código
# =============================================================================
import os
from google.colab import userdata

# OpenAI API Key — necesaria para embeddings y GPT-4o
try:
    os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY').strip()
    print('✅ OPENAI_API_KEY cargada')
except Exception:
    print('❌ OPENAI_API_KEY — agrégala en el panel 🔑')

# Telegram Bot Token — obtenido de @BotFather en Telegram
try:
    TELEGRAM_TOKEN = userdata.get('TELEGRAM_BOT_TOKEN').strip()
    print('✅ TELEGRAM_BOT_TOKEN cargado')
except Exception:
    TELEGRAM_TOKEN = None
    print('❌ TELEGRAM_BOT_TOKEN — agrégalo en el panel 🔑')

# ── Configuración global del sistema ──────────────────────────────────────────
# Todos los parámetros centralizados aquí para fácil ajuste
CONFIG = {
    'llm_model'        : 'gpt-4o',           # Modelo LLM de OpenAI
    'temperature'      : 0.1,                # Muy bajo: respuestas más precisas y conservadoras
    'chunk_size'       : 800,                # Tamaño de fragmentos (más pequeño = más precisión)
    'chunk_overlap'    : 150,                # Solapamiento para no perder contexto entre chunks
    'retriever_k'      : 5,                  # Fragmentos recuperados por consulta
    'docs_dir'         : '/content/docs_pqrs/',   # Directorio con los PDFs de Mercado Libre
    'db_path'          : '/content/pqrs_ml.db',   # Base de datos SQLite
    'faiss_index_path' : '/content/faiss_ml_index', # Índice vectorial FAISS persistente
}

print('\n✅ Configuración global cargada:')
for k, v in CONFIG.items():
    print(f'   {k:<22}: {v}')

"""## 🗄️ Paso 3 — Base de datos SQLite"""

# =============================================================================
# PASO 3: Configurar SQLite para registrar todas las interacciones PQRS
# Tabla: pqrs_logs | Campos: id, fecha, usuario, chat_id, pregunta,
#                            respuesta, tipo_pqrs, documento_fuente, pagina_fuente
# =============================================================================
import sqlite3
from datetime import datetime

# Script DDL — define la estructura de la tabla de registros
SQL_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS pqrs_logs (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    fecha            TEXT    NOT NULL,
    usuario          TEXT    NOT NULL,
    chat_id          TEXT    NOT NULL,
    pregunta         TEXT    NOT NULL,
    respuesta        TEXT    NOT NULL,
    tipo_pqrs        TEXT    NOT NULL,
    documento_fuente TEXT,
    pagina_fuente    TEXT,
    score_similitud  REAL
);
"""

def init_db() -> sqlite3.Connection:
    """Inicializa la base de datos SQLite y retorna la conexión activa."""
    conn = sqlite3.connect(CONFIG['db_path'], check_same_thread=False)
    conn.execute(SQL_CREATE_TABLE)
    conn.commit()
    return conn

def registrar_pqrs(
    conn: sqlite3.Connection,
    usuario: str,
    chat_id: str,
    pregunta: str,
    respuesta: str,
    tipo_pqrs: str,
    documento_fuente: str = None,
    pagina_fuente: str = None,
    score_similitud: float = None
) -> int:
    """Registra una consulta PQRS en la base de datos y retorna el id."""
    fecha = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    cursor = conn.execute(
        """
        INSERT INTO pqrs_logs
            (fecha, usuario, chat_id, pregunta, respuesta,
             tipo_pqrs, documento_fuente, pagina_fuente, score_similitud)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (fecha, usuario, chat_id, pregunta, respuesta,
         tipo_pqrs, documento_fuente, pagina_fuente, score_similitud)
    )
    conn.commit()
    return cursor.lastrowid

def obtener_estadisticas(conn: sqlite3.Connection) -> dict:
    """Devuelve estadísticas de uso del sistema PQRS para el comando /estadisticas."""
    total    = conn.execute('SELECT COUNT(*) FROM pqrs_logs').fetchone()[0]
    por_tipo = conn.execute(
        'SELECT tipo_pqrs, COUNT(*) as cnt FROM pqrs_logs GROUP BY tipo_pqrs ORDER BY cnt DESC'
    ).fetchall()
    por_doc  = conn.execute(
        'SELECT documento_fuente, COUNT(*) as cnt FROM pqrs_logs '
        'WHERE documento_fuente IS NOT NULL GROUP BY documento_fuente ORDER BY cnt DESC LIMIT 5'
    ).fetchall()
    return {
        'total'   : total,
        'por_tipo': dict(por_tipo),
        'por_doc' : dict(por_doc)
    }

# Inicializar la base de datos
db_conn = init_db()
print('✅ SQLite inicializado en:', CONFIG['db_path'])
print('   Tabla pqrs_logs creada/verificada.')

"""## 🤖 Paso 4 — Clasificador PQRS con Random Forest + TF-IDF"""

# =============================================================================
# PASO 4: IA Clásica — Clasificador PQRS adaptado a Mercado Libre
# Pipeline: limpieza de texto → TF-IDF (bigramas) → Random Forest
# Categorías: Petición | Queja | Reclamo | Sugerencia
# Dataset entrenado con vocabulario propio de e-commerce y Mercado Libre
# =============================================================================
import re
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)
from sklearn.pipeline import Pipeline

# ── Dataset de entrenamiento — dominio Mercado Libre / e-commerce ─────────────
# Ejemplos representativos de consultas reales de usuarios de Mercado Libre.
# En producción, ampliar con datos reales de la plataforma.
DATOS_ENTRENAMIENTO = [
    # ── PETICIÓN: solicitudes de información o procesos ──────────────────────
    ('Quiero saber cómo hacer una devolución de un producto', 'Petición'),
    ('Necesito información sobre el proceso de reembolso', 'Petición'),
    ('¿Cómo funciona el programa de Compra Protegida?', 'Petición'),
    ('¿Cuánto tiempo tengo para devolver un producto?', 'Petición'),
    ('Quiero saber cuáles son los medios de pago aceptados', 'Petición'),
    ('¿Cómo puedo solicitar una factura de mi compra?', 'Petición'),
    ('Necesito saber cuándo me acreditan el dinero del reembolso', 'Petición'),
    ('¿Cómo puedo registrarme en Mercado Pago?', 'Petición'),
    ('¿Cuáles son los plazos para recibir mi pedido?', 'Petición'),
    ('¿Qué productos no tienen devolución?', 'Petición'),
    ('¿Cómo funciona el seguro de envío con Mercado Envíos?', 'Petición'),
    ('Necesito saber cómo cancelar una compra antes del envío', 'Petición'),
    ('¿Qué debo hacer si recibí el paquete dañado?', 'Petición'),
    ('¿Cómo puedo hacer seguimiento a mi devolución?', 'Petición'),
    ('Solicito información sobre las tarifas de Mercado Pago', 'Petición'),
    # ── QUEJA: insatisfacción con el servicio o experiencia ──────────────────
    ('El vendedor nunca me respondió y el servicio es muy malo', 'Queja'),
    ('Estoy muy insatisfecho con la atención al cliente de Mercado Libre', 'Queja'),
    ('El proceso de devolución es demasiado complicado y tardado', 'Queja'),
    ('Me parece pésimo que no me hayan notificado del retraso', 'Queja'),
    ('La plataforma falla constantemente y no puedo completar mi compra', 'Queja'),
    ('El servicio de Mercado Envíos es muy deficiente', 'Queja'),
    ('Llevo semanas esperando respuesta y nadie me ayuda', 'Queja'),
    ('Es inaceptable que el sistema no permita rastrear mi paquete', 'Queja'),
    ('La aplicación móvil es muy lenta y da muchos errores', 'Queja'),
    ('Me siento ignorado por el soporte de Mercado Libre', 'Queja'),
    ('El tiempo de espera para resolver reclamos es demasiado largo', 'Queja'),
    ('Estoy muy molesto con la forma en que gestionaron mi caso', 'Queja'),
    # ── RECLAMO: exigencia formal de corrección o derecho ────────────────────
    ('Recibí un producto diferente al que compré y exijo la devolución', 'Reclamo'),
    ('El producto llegó defectuoso y reclamo el reembolso completo', 'Reclamo'),
    ('No recibí mi pedido y exijo que me devuelvan el dinero', 'Reclamo'),
    ('Me hicieron un cobro duplicado y exijo que lo reembolsen', 'Reclamo'),
    ('El vendedor incumplió lo prometido y reclamo una solución', 'Reclamo'),
    ('Reclamo porque el paquete llegó con contenido incompleto', 'Reclamo'),
    ('Exijo que se respete la garantía del producto que compré', 'Reclamo'),
    ('El artículo no corresponde a la descripción y reclamo mi dinero', 'Reclamo'),
    ('Reclamo porque el reembolso no fue acreditado en los plazos prometidos', 'Reclamo'),
    ('El seguro de compra no cubrió mi caso y exijo revisión', 'Reclamo'),
    ('Me descontaron dinero sin autorización de mi cuenta Mercado Pago', 'Reclamo'),
    ('El correo perdió mi devolución y exijo que se resuelva', 'Reclamo'),
    # ── SUGERENCIA: propuestas de mejora a la plataforma ─────────────────────
    ('Propongo implementar notificaciones en tiempo real para los envíos', 'Sugerencia'),
    ('Sugiero que el proceso de devolución sea más sencillo y rápido', 'Sugerencia'),
    ('Recomiendo agregar más métodos de pago como criptomonedas', 'Sugerencia'),
    ('Sería útil tener un chat en vivo con soporte las 24 horas', 'Sugerencia'),
    ('Propongo un sistema de reseñas verificadas para los vendedores', 'Sugerencia'),
    ('Sugiero mejorar la interfaz de seguimiento de pedidos', 'Sugerencia'),
    ('Recomiendo implementar devoluciones sin necesidad de etiqueta física', 'Sugerencia'),
    ('Propongo un programa de fidelidad para compradores frecuentes', 'Sugerencia'),
    ('Sería excelente tener un asistente virtual integrado en la app', 'Sugerencia'),
    ('Sugiero que la resolución de reclamos sea más transparente', 'Sugerencia'),
    ('Recomiendo agregar filtros por garantía en los resultados de búsqueda', 'Sugerencia'),
    ('Propongo que se muestre el historial de precios del producto', 'Sugerencia'),
]

# ── Función de limpieza y normalización de texto ──────────────────────────────
def limpiar_texto(texto: str) -> str:
    """Normaliza el texto para el clasificador: minúsculas, solo letras y espacios."""
    texto = texto.lower()
    texto = re.sub(r'[^a-záéíóúüñ\s]', ' ', texto)  # Solo letras españolas y espacios
    texto = re.sub(r'\s+', ' ', texto).strip()        # Eliminar espacios múltiples
    return texto

# ── Preparar datos para entrenamiento y evaluación ────────────────────────────
textos    = [limpiar_texto(t) for t, _ in DATOS_ENTRENAMIENTO]
etiquetas = [e for _, e in DATOS_ENTRENAMIENTO]

# Dividir en entrenamiento (75%) y prueba (25%) de forma estratificada
X_train, X_test, y_train, y_test = train_test_split(
    textos, etiquetas, test_size=0.25, random_state=42, stratify=etiquetas
)

# ── Pipeline: TF-IDF + Random Forest ─────────────────────────────────────────
# TfidfVectorizer: convierte texto en vectores numéricos ponderados por frecuencia
# RandomForestClassifier: ensemble de árboles de decisión para clasificación
pipeline_clasificador = Pipeline([
    ('tfidf', TfidfVectorizer(
        ngram_range=(1, 2),   # Unigramas y bigramas para capturar frases clave
        max_features=8000,    # Vocabulario más amplio para dominio e-commerce
        sublinear_tf=True,    # Escala logarítmica para TF
        min_df=1              # Incluir términos poco frecuentes (dataset pequeño)
    )),
    ('clf', RandomForestClassifier(
        n_estimators=300,     # Más árboles = mayor estabilidad
        max_depth=None,
        random_state=42,
        n_jobs=-1             # Usar todos los núcleos disponibles
    ))
])

# ── Entrenamiento del clasificador ────────────────────────────────────────────
pipeline_clasificador.fit(X_train, y_train)

# ── Evaluación del modelo ─────────────────────────────────────────────────────
y_pred = pipeline_clasificador.predict(X_test)

accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
recall    = recall_score(y_test, y_pred, average='weighted', zero_division=0)
f1        = f1_score(y_test, y_pred, average='weighted', zero_division=0)

print('\n📊 MÉTRICAS DEL CLASIFICADOR RANDOM FOREST')
print('=' * 45)
print(f'  Accuracy  : {accuracy:.4f}  ({accuracy*100:.1f}%)')
print(f'  Precision : {precision:.4f}')
print(f'  Recall    : {recall:.4f}')
print(f'  F1-Score  : {f1:.4f}')
print(f'\n{classification_report(y_test, y_pred, zero_division=0)}')

# ── Función de clasificación PQRS (interfaz pública) ─────────────────────────
def clasificar_pqrs(texto: str) -> dict:
    """
    Clasifica una consulta de usuario en: Petición, Queja, Reclamo o Sugerencia.
    Retorna dict con 'categoria' y 'confianza' (probabilidad del modelo).
    """
    texto_limpio = limpiar_texto(texto)
    categoria    = pipeline_clasificador.predict([texto_limpio])[0]
    probabilidades = pipeline_clasificador.predict_proba([texto_limpio])[0]
    confianza    = max(probabilidades)
    return {'categoria': categoria, 'confianza': confianza}

# ── Prueba rápida del clasificador ────────────────────────────────────────────
print('\n🧪 Prueba del clasificador con consultas de Mercado Libre:')
ejemplos_prueba = [
    '¿Cuánto tiempo tengo para devolver un producto en Mercado Libre?',
    'El producto llegó dañado y estoy muy molesto con el servicio',
    'No recibí mi pedido y exijo que me devuelvan el dinero ya',
    'Propongo que agreguen más métodos de pago a la plataforma',
]
for ej in ejemplos_prueba:
    res = clasificar_pqrs(ej)
    print(f'  ▶ "{ej[:60]}..."')
    print(f'    → {res["categoria"]} (confianza: {res["confianza"]:.2%})')

"""## 📊 Paso 5 — Visualizaciones del Clasificador"""

# =============================================================================
# PASO 5: Visualizaciones académicas del clasificador PQRS
# Gráficas: Matriz de confusión | Distribución PQRS | F1 por categoría
# =============================================================================
from collections import Counter
from sklearn.metrics import f1_score

categorias = ['Petición', 'Queja', 'Reclamo', 'Sugerencia']
colores    = ['#3498db', '#e74c3c', '#e67e22', '#2ecc71']

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle(
    '📊 Análisis del Clasificador PQRS — Mercado Libre (RF + TF-IDF)',
    fontsize=14, fontweight='bold', y=1.02
)

# ── 1. Matriz de confusión ────────────────────────────────────────────────────
cm = confusion_matrix(y_test, y_pred, labels=categorias)
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=categorias, yticklabels=categorias,
    ax=axes[0], linewidths=0.5
)
axes[0].set_title('Matriz de Confusión', fontweight='bold')
axes[0].set_xlabel('Predicho')
axes[0].set_ylabel('Real')
axes[0].tick_params(axis='x', rotation=30)

# ── 2. Distribución del dataset de entrenamiento ──────────────────────────────
conteo = Counter(etiquetas)
bars   = axes[1].bar(conteo.keys(), conteo.values(), color=colores, edgecolor='white', linewidth=1.5)
axes[1].set_title('Distribución del Dataset PQRS\n(Mercado Libre)', fontweight='bold')
axes[1].set_ylabel('Cantidad de ejemplos')
axes[1].set_xlabel('Categoría')
for bar in bars:
    axes[1].text(
        bar.get_x() + bar.get_width() / 2.,
        bar.get_height() + 0.1,
        str(int(bar.get_height())),
        ha='center', va='bottom', fontweight='bold'
    )

# ── 3. F1-Score por categoría PQRS ────────────────────────────────────────────
clases_disponibles = list(pipeline_clasificador.classes_)
f1_ordenado = []
for cat in categorias:
    if cat in clases_disponibles:
        f1_val = f1_score(y_test, y_pred, labels=[cat], average='macro', zero_division=0)
        f1_ordenado.append(f1_val)
    else:
        f1_ordenado.append(0.0)

bars2 = axes[2].bar(categorias, f1_ordenado, color=colores, edgecolor='white', linewidth=1.5)
axes[2].set_title('F1-Score por Categoría PQRS', fontweight='bold')
axes[2].set_ylabel('F1-Score')
axes[2].set_ylim(0, 1.15)
axes[2].axhline(y=0.8, color='red', linestyle='--', alpha=0.6, label='Umbral mínimo (0.80)')
axes[2].legend(fontsize=8)
for bar, val in zip(bars2, f1_ordenado):
    axes[2].text(
        bar.get_x() + bar.get_width() / 2.,
        bar.get_height() + 0.02,
        f'{val:.2f}',
        ha='center', va='bottom', fontweight='bold'
    )

plt.tight_layout()
plt.savefig('/content/metricas_clasificador_ml.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Visualizaciones guardadas en /content/metricas_clasificador_ml.png')

"""## 📄 Paso 6 — Subir PDFs y construir Vector

"""

from google.colab import drive
drive.mount('/content/drive')

# =============================================================================
# PASO 6a: Cargar PDFs desde Google Drive
# =============================================================================

from google.colab import drive
import os

# Montar Google Drive
drive.mount('/content/drive')

# Ruta de la carpeta que contiene los PDFs
CONFIG['docs_dir'] = "/content/drive/MyDrive/Base Documental"

# Verificar que la carpeta exista
if not os.path.exists(CONFIG['docs_dir']):
    raise FileNotFoundError(
        f"No existe la carpeta: {CONFIG['docs_dir']}"
    )

# Buscar PDFs
pdfs_disponibles = [
    f for f in os.listdir(CONFIG['docs_dir'])
    if f.lower().endswith('.pdf')
]

print(f"\n📁 PDFs encontrados en:")
print(CONFIG['docs_dir'])

for pdf in pdfs_disponibles:
    print(f"   • {pdf}")

print(f"\n✅ Total PDFs encontrados: {len(pdfs_disponibles)}")

# =============================================================================
# PASO 6b: Construir el sistema RAG con los PDFs de Mercado Libre
# Flujo: PyPDFLoader → RecursiveCharacterTextSplitter → Embeddings → FAISS
# Cada fragmento conserva metadata: nombre del PDF y número de página
# IMPORTANTE: El sistema SOLO usa estos PDFs como fuente de conocimiento
# =============================================================================
import os
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

def cargar_pdfs_mercadolibre(directorio: str) -> list:
    """
    Carga automáticamente todos los PDFs de un directorio usando PyPDFLoader.
    Enriquece cada documento con metadata: nombre del PDF y número de página.
    Si no hay PDFs, informa al usuario cómo proceder.
    """
    documentos = []
    archivos_pdf = sorted([f for f in os.listdir(directorio) if f.endswith('.pdf')])

    if not archivos_pdf:
        print('⚠️  No se encontraron PDFs en', directorio)
        print('   Por favor sube los PDFs en el Paso 6a y vuelve a ejecutar esta celda.')
        return []

    for nombre_pdf in archivos_pdf:
        ruta = os.path.join(directorio, nombre_pdf)
        try:
            # PyPDFLoader carga cada página como un documento independiente
            loader = PyPDFLoader(ruta)
            paginas = loader.load()
            # Enriquecer metadata con nombre legible del archivo
            for pag in paginas:
                pag.metadata['source'] = nombre_pdf
                pag.metadata['doc_type'] = 'mercadolibre_oficial'
            documentos.extend(paginas)
            print(f'  ✅ {nombre_pdf}: {len(paginas)} página(s) cargadas')
        except Exception as e:
            print(f'  ❌ Error cargando {nombre_pdf}: {e}')

    return documentos


def construir_vector_store_faiss(documentos: list, forzar_reconstruccion: bool = False) -> FAISS:
    """
    Construye o carga el índice vectorial FAISS.
    - Si el índice ya existe en disco y no se fuerza reconstrucción: lo carga.
    - Si no existe: fragmenta docs → genera embeddings → construye FAISS → persiste.
    Usa RecursiveCharacterTextSplitter para dividir respetando párrafos y oraciones.
    """
    # Modelo de embeddings: text-embedding-3-small (bajo costo, alta calidad)
    embeddings = OpenAIEmbeddings(model='text-embedding-3-small')

    # Intentar cargar índice FAISS existente desde disco
    if os.path.exists(CONFIG['faiss_index_path']) and not forzar_reconstruccion:
        print('📂 Cargando índice FAISS existente desde disco...')
        vs = FAISS.load_local(
            CONFIG['faiss_index_path'],
            embeddings,
            allow_dangerous_deserialization=True  # Necesario para FAISS local
        )
        print(f'✅ Índice FAISS cargado correctamente.')
        return vs

    if not documentos:
        raise ValueError('No hay documentos para indexar. Sube los PDFs primero.')

    # Fragmentar documentos con RecursiveCharacterTextSplitter
    # Los separadores respetan la estructura natural del texto (párrafos > líneas > oraciones)
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CONFIG['chunk_size'],
        chunk_overlap=CONFIG['chunk_overlap'],
        separators=['\n\n', '\n', '. ', ', ', ' ', '']  # Jerarquía de separadores
    )
    fragmentos = splitter.split_documents(documentos)

    print(f'\n📋 Fragmentación completada:')
    print(f'   • Documentos originales (páginas) : {len(documentos)}')
    print(f'   • Fragmentos generados             : {len(fragmentos)}')
    print(f'   • Tamaño por fragmento             : {CONFIG["chunk_size"]} chars')
    print(f'   • Solapamiento                     : {CONFIG["chunk_overlap"]} chars')

    # Generar embeddings y construir el índice FAISS
    print('\n🔄 Generando embeddings (OpenAI text-embedding-3-small)...')
    print('   Esto puede tardar 1-2 minutos dependiendo del tamaño de los PDFs...')
    vector_store = FAISS.from_documents(fragmentos, embeddings)

    # Persistir el índice en disco para reutilización en sesiones futuras
    vector_store.save_local(CONFIG['faiss_index_path'])
    print(f'\n✅ Índice FAISS construido y guardado en: {CONFIG["faiss_index_path"]}')

    return vector_store


# ── Ejecutar pipeline de carga y construcción RAG ─────────────────────────────
print('📄 CARGANDO BASE DOCUMENTAL MERCADO LIBRE')
print('=' * 45)

documentos_raw = cargar_pdfs_mercadolibre(CONFIG['docs_dir'])
vector_store   = construir_vector_store_faiss(documentos_raw)

# Crear retriever con búsqueda por similitud semántica
retriever = vector_store.as_retriever(
    search_type='similarity',
    search_kwargs={'k': CONFIG['retriever_k']}
)

print(f'\n✅ Sistema RAG listo. Recuperará {CONFIG["retriever_k"]} fragmentos por consulta.')
print(f'   Fuente exclusiva: PDFs oficiales de Mercado Libre en {CONFIG["docs_dir"]}')

"""## 🔗 Paso 7 — Cadena Principal LangChain (Pipeline PQRS Mercado Libre)"""

# =============================================================================
# PASO 7: Cadena principal LangChain para PQRS Mercado Libre
# Flujo: Clasificación PQRS → Retriever FAISS → PromptTemplate → LLM → Parser
# REGLA FUNDAMENTAL: El LLM responde ÚNICAMENTE con info de los PDFs recuperados
# Si la información no está en los documentos → respuesta de fallback explícita
# =============================================================================
import warnings
warnings.filterwarnings('ignore')

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# ── Modelo LLM (GPT-4o con temperatura baja para mayor precisión) ─────────────
llm = ChatOpenAI(
    model=CONFIG['llm_model'],
    temperature=CONFIG['temperature']
)

# ── Prompt del sistema — especializado en PQRS de Mercado Libre ───────────────
# El prompt está diseñado para:
# 1. Restringir respuestas EXCLUSIVAMENTE a los PDFs recuperados
# 2. Citar siempre el documento fuente y la página
# 3. Dar respuesta de fallback si la información no existe en los documentos
# 4. Adaptar el tono según el tipo PQRS (Petición/Queja/Reclamo/Sugerencia)
SYSTEM_PROMPT_ML = """Eres un asistente inteligente de PQRS (Peticiones, Quejas, Reclamos y Sugerencias) \
especializado en Mercado Libre Colombia.

TU ÚNICA FUENTE DE INFORMACIÓN son los fragmentos de documentos oficiales de Mercado Libre que se te \
proporcionan como CONTEXTO DOCUMENTAL a continuación. Estos documentos incluyen:
- Términos y Condiciones de Mercado Libre
- Políticas de devolución de productos
- Cómo devolver un producto
- Condiciones del programa Compra Protegida

REGLAS ESTRICTAS — debes seguirlas sin excepción:
1. NUNCA uses conocimiento general del LLM. Solo responde con información presente en el CONTEXTO DOCUMENTAL.
2. Si la información solicitada NO aparece en los fragmentos recuperados, responde exactamente:
   "No encontré información suficiente en la documentación oficial de Mercado Libre."
3. Genera respuestas claras, profesionales y en español de Colombia.
4. SIEMPRE cita el documento fuente y la página específica donde encontraste la información.
5. La consulta ha sido clasificada automáticamente como: {tipo_pqrs} (confianza: {confianza}).
6. Adapta el tono según el tipo de PQRS:
   - Petición → informativo y servicial
   - Queja → empático y comprensivo, explica el proceso según el documento
   - Reclamo → formal, indica los pasos y derechos según los documentos
   - Sugerencia → agradecido, orienta sobre cómo proceder

FORMATO DE RESPUESTA OBLIGATORIO:
📋 Tipo de consulta: [Petición / Queja / Reclamo / Sugerencia]

📝 Respuesta:
[Respuesta basada EXCLUSIVAMENTE en los documentos recuperados]

📄 Fuente documental:
• Documento: [nombre exacto del PDF]
• Página: [número de página]

---
CONTEXTO DOCUMENTAL RECUPERADO (fragmentos de los PDFs oficiales de Mercado Libre):
{contexto}
"""

# Crear el prompt template de LangChain con variables: tipo_pqrs, confianza, contexto, pregunta
prompt_pqrs_ml = ChatPromptTemplate.from_messages([
    ('system', SYSTEM_PROMPT_ML),
    ('human', '{pregunta}')
])

# ── Función para formatear documentos recuperados por FAISS ──────────────────
def formatear_contexto(docs: list) -> str:
    """
    Convierte la lista de fragmentos recuperados por FAISS en un bloque de texto
    estructurado con metadata visible (fuente y página) para el LLM.
    """
    bloques = []
    for i, doc in enumerate(docs, 1):
        fuente = doc.metadata.get('source', 'Documento desconocido')
        pagina = doc.metadata.get('page', 'N/A')
        # Limpiar el nombre del archivo para presentación
        nombre_limpio = fuente.replace('_', ' ').replace('.pdf', '')
        bloque = (
            f"[Fragmento {i} | Documento: {nombre_limpio} | Página: {pagina}]\n"
            f"{doc.page_content.strip()}"
        )
        bloques.append(bloque)
    return '\n\n---\n\n'.join(bloques)


def extraer_fuente_principal(docs: list) -> tuple:
    """
    Retorna (documento_principal, páginas_citadas) basado en los fragmentos recuperados.
    El documento principal es el que aparece más veces en los resultados.
    """
    from collections import Counter
    if not docs:
        return ('Sin fuente', 'N/A')
    fuentes = [doc.metadata.get('source', 'desconocido') for doc in docs]
    paginas = sorted(set(
        str(doc.metadata.get('page', 'N/A'))
        for doc in docs
        if doc.metadata.get('source') == Counter(fuentes).most_common(1)[0][0]
    ))
    doc_principal = Counter(fuentes).most_common(1)[0][0]
    paginas_str   = ', '.join(paginas)
    return (doc_principal, paginas_str)


# ── Función principal: pipeline PQRS completo ─────────────────────────────────
def procesar_pqrs(pregunta: str, usuario: str = 'usuario', chat_id: str = '0') -> dict:
    """
    Ejecuta el pipeline completo de PQRS para Mercado Libre:
    A. Clasificar consulta (Random Forest + TF-IDF)
    B. Recuperar fragmentos relevantes (FAISS RAG)
    C. Generar respuesta (GPT-4o con contexto documental)
    D. Registrar en SQLite
    E. Retornar resultado estructurado

    Returns:
        dict con: id_registro, tipo_pqrs, confianza, respuesta,
                  fuente_doc, pagina_fuente, n_fragmentos
    """
    # ── A: Clasificación PQRS con Random Forest ────────────────────────────────
    clasificacion = clasificar_pqrs(pregunta)
    tipo_pqrs     = clasificacion['categoria']
    confianza     = clasificacion['confianza']

    # ── B: Recuperación RAG desde FAISS ───────────────────────────────────────
    # El retriever devuelve los k fragmentos más similares semánticamente
    docs_relevantes = retriever.invoke(pregunta)
    contexto        = formatear_contexto(docs_relevantes)
    fuente_doc, pagina_fuente = extraer_fuente_principal(docs_relevantes)

    # ── C: Generación de respuesta con LangChain + LLM ────────────────────────
    # La cadena: prompt → LLM → parser de texto plano
    chain     = prompt_pqrs_ml | llm | StrOutputParser()
    respuesta = chain.invoke({
        'pregunta'  : pregunta,
        'tipo_pqrs' : tipo_pqrs,
        'confianza' : f'{confianza:.1%}',
        'contexto'  : contexto
    })

    # ── D: Registro en SQLite para auditoría ──────────────────────────────────
    id_registro = registrar_pqrs(
        conn=db_conn,
        usuario=usuario,
        chat_id=chat_id,
        pregunta=pregunta,
        respuesta=respuesta,
        tipo_pqrs=tipo_pqrs,
        documento_fuente=fuente_doc,
        pagina_fuente=pagina_fuente,
        score_similitud=confianza
    )

    # ── E: Retornar resultado estructurado ─────────────────────────────────────
    return {
        'id_registro'   : id_registro,
        'tipo_pqrs'     : tipo_pqrs,
        'confianza'     : confianza,
        'respuesta'     : respuesta,
        'fuente_doc'    : fuente_doc,
        'pagina_fuente' : pagina_fuente,
        'n_fragmentos'  : len(docs_relevantes)
    }


print('✅ Cadena LangChain PQRS Mercado Libre configurada.')
print('   Pipeline: Clasificador RF → FAISS Retriever → PromptTemplate → GPT-4o → Parser')

# ── Prueba de la cadena completa ───────────────────────────────────────────────
print('\n🧪 Prueba de la cadena completa:')
resultado_prueba = procesar_pqrs(
    '¿Cuánto tiempo tengo para devolver un producto y cómo funciona el reembolso?',
    usuario='test_user',
    chat_id='000'
)
print(f'\n  Tipo PQRS   : {resultado_prueba["tipo_pqrs"]} ({resultado_prueba["confianza"]:.1%})')
print(f'  Fragmentos  : {resultado_prueba["n_fragmentos"]} recuperados')
print(f'  Fuente      : {resultado_prueba["fuente_doc"]}')
print(f'  Página(s)   : {resultado_prueba["pagina_fuente"]}')
print(f'\n  Respuesta:\n{resultado_prueba["respuesta"]}')

"""## 🤖 Paso 8 — Bot de Telegram (Handlers y lógica)"""

# =============================================================================
# PASO 8: Definir los handlers del bot de Telegram para PQRS Mercado Libre
# Comandos: /start, /ayuda, /estadisticas
# Mensajes de texto → pipeline PQRS completo
# El bot captura: chat_id, username, fecha, mensaje
# =============================================================================
from telegram import Update
from telegram.ext import (
    Application, CommandHandler, MessageHandler,
    filters, ContextTypes
)
from datetime import datetime

# ── /start — mensaje de bienvenida con menú de temas ─────────────────────────
async def cmd_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    nombre = update.effective_user.first_name
    await update.message.reply_text(
        f'🛒 *Bienvenido/a {nombre} al Asistente PQRS de Mercado Libre*\n\n'
        'Puedo responder preguntas sobre:\n'
        '  📦 Devoluciones de productos\n'
        '  💰 Reembolsos y acreditaciones\n'
        '  🛡️ Compra Protegida\n'
        '  ⚖️ Reclamos y garantías\n'
        '  📜 Términos y condiciones\n'
        '  💳 Mercado Pago\n'
        '  🚚 Envíos y cancelaciones\n\n'
        '📋 *Comandos disponibles:*\n'
        '  /start         → Mensaje de bienvenida\n'
        '  /ayuda         → Cómo formular tu consulta\n'
        '  /estadisticas  → Estadísticas del sistema\n\n'
        '💬 Escribe tu consulta directamente para comenzar.\n'
        '_Toda la información proviene de la documentación oficial de Mercado Libre._',
        parse_mode='Markdown'
    )

# ── /ayuda — guía para formular PQRS en contexto Mercado Libre ───────────────
async def cmd_ayuda(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        '📘 *Guía para formular tu consulta PQRS:*\n\n'
        '• *Petición:* Solicitud de información sobre procesos.\n'
        '  _"¿Cómo devuelvo un producto?"_\n'
        '  _"¿Cuáles son los plazos de devolución?"_\n\n'
        '• *Queja:* Insatisfacción con el servicio.\n'
        '  _"El proceso de devolución es muy complicado"_\n'
        '  _"El vendedor no me respondió"_\n\n'
        '• *Reclamo:* Exigencia formal de solución.\n'
        '  _"Recibí el producto dañado y exijo el reembolso"_\n'
        '  _"No llegó mi pedido y reclamo mi dinero"_\n\n'
        '• *Sugerencia:* Propuesta de mejora.\n'
        '  _"Propongo notificaciones en tiempo real"_\n\n'
        '🤖 El sistema clasifica tu consulta automáticamente y responde\n'
        'basándose *exclusivamente* en los documentos oficiales de Mercado Libre.',
        parse_mode='Markdown'
    )

# ── /estadisticas — muestra métricas de uso del sistema ─────────────────────
async def cmd_estadisticas(update: Update, context: ContextTypes.DEFAULT_TYPE):
    stats = obtener_estadisticas(db_conn)
    msg   = '📊 *Estadísticas del Sistema PQRS — Mercado Libre*\n\n'
    msg  += f'Total de consultas procesadas: *{stats["total"]}*\n\n'
    msg  += '*Distribución por tipo:*\n'
    emojis = {'Petición': '📋', 'Queja': '😤', 'Reclamo': '⚖️', 'Sugerencia': '💡'}
    for tipo, cantidad in stats['por_tipo'].items():
        emoji = emojis.get(tipo, '📌')
        msg  += f'  {emoji} {tipo}: {cantidad}\n'
    if stats['por_doc']:
        msg += '\n*Documentos más consultados:*\n'
        for doc, cnt in list(stats['por_doc'].items())[:3]:
            nombre_corto = doc.replace('_', ' ').replace('.pdf', '')[:35]
            msg += f'  📄 {nombre_corto}: {cnt}\n'
    await update.message.reply_text(msg, parse_mode='Markdown')

# ── handler principal: mensajes de texto → pipeline PQRS ─────────────────────
async def handle_mensaje(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handler principal del bot:
    1. Extrae datos del usuario (chat_id, username, texto)
    2. Envía indicador 'escribiendo...' para mejor UX
    3. Ejecuta el pipeline PQRS completo
    4. Formatea la respuesta con emoji según tipo PQRS
    5. Envía respuesta al usuario con fuente documental
    """
    chat_id = str(update.effective_chat.id)
    usuario = update.effective_user.username or update.effective_user.first_name
    texto   = update.message.text

    # Indicador de 'escribiendo...' mientras se procesa (mejor UX)
    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action='typing')

    try:
        # Ejecutar el pipeline PQRS completo
        resultado = procesar_pqrs(
            pregunta=texto,
            usuario=usuario,
            chat_id=chat_id
        )

        # Formatear respuesta con emoji según el tipo de PQRS detectado
        emojis_tipo = {
            'Petición'   : '📋',
            'Queja'      : '😤',
            'Reclamo'    : '⚖️',
            'Sugerencia' : '💡'
        }
        emoji = emojis_tipo.get(resultado['tipo_pqrs'], '📌')

        # Construir mensaje de respuesta para Telegram
        respuesta_telegram = (
            f"{emoji} *{resultado['tipo_pqrs']}* "
            f"_(confianza: {resultado['confianza']:.0%})_\n\n"
            f"{resultado['respuesta']}\n\n"
            f"_🔍 Fragmentos consultados: {resultado['n_fragmentos']}_\n"
            f"_📄 Fuente: {resultado['fuente_doc'].replace('_', ' ')}_"
        )

        # Telegram tiene límite de 4096 chars por mensaje
        if len(respuesta_telegram) > 4096:
            respuesta_telegram = respuesta_telegram[:4090] + '...'

        await update.message.reply_text(
            respuesta_telegram,
            parse_mode='Markdown'
        )

    except Exception as e:
        # En caso de error, informar al usuario y registrar en consola
        print(f'❌ Error procesando consulta de {usuario}: {e}')
        await update.message.reply_text(
            '⚠️ Ocurrió un error al procesar tu consulta.\n'
            'Por favor intenta de nuevo en unos momentos.'
        )

print('✅ Handlers definidos: cmd_start, cmd_ayuda, cmd_estadisticas, handle_mensaje')

"""## 🚀 Paso 9 — Iniciar el Bot de Telegram"""

# =============================================================================
# PASO 9: Iniciar el bot de Telegram con python-telegram-bot 20+
# NOTA: run_polling() bloquea la celda. Para detener, interrumpe el kernel.
# Correcciones aplicadas:
# - stop_signals=None: evita crash en Python 3.12 en hilo secundario de Colab
# - close_loop=False:  evita inconsistencias del event loop al detener
# =============================================================================
import asyncio
import nest_asyncio

# Aplicar nest_asyncio para permitir la ejecución anidada del event loop
nest_asyncio.apply()

if TELEGRAM_TOKEN is None:
    print('❌ No se puede iniciar el bot: falta el TELEGRAM_BOT_TOKEN')
    print('   Agrégalo en el panel de Secrets (🔑) de Colab y vuelve a ejecutar.')
else:
    print('🤖 Iniciando bot de Telegram — PQRS Mercado Libre...')
    print('   Detener: Runtime → Interrupt execution (o Ctrl+C)\n')

    # Construir la aplicación del bot
    app = Application.builder().token(TELEGRAM_TOKEN).build()

    # Registrar handlers de comandos
    app.add_handler(CommandHandler('start',        cmd_start))
    app.add_handler(CommandHandler('ayuda',        cmd_ayuda))
    app.add_handler(CommandHandler('estadisticas', cmd_estadisticas))

    # Registrar handler de mensajes de texto (excluye comandos)
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_mensaje))

    print('✅ Handlers registrados.')
    print('🟢 Bot activo. Envía un mensaje en Telegram para comenzar.\n')
    print('🟢 /start --> Inicias chat.\n')
    print('🟢 /ayuda --> Te ayuda a preguntar al bot.\n')
    print('🟢 /estadistica --> Te muestra cuantas consultas existen de la base documental.\n')

    # Iniciar el polling con configuración compatible con Colab (Python 3.12)
    app.run_polling(
        stop_signals=None,   # Evita crash en hilo secundario de Colab
        close_loop=False     # Evita conflicto con el event loop de Colab
    )

"""## 🧪 Paso 10 — Casos de Prueba (sin Telegram)"""

# =============================================================================
# PASO 10: Ejecutar casos de prueba automatizados para validar el sistema
# Permite probar el pipeline PQRS sin necesidad de Telegram
# Cubre los 9 temas del asistente: devoluciones, reembolsos, Compra Protegida,
# reclamos, T&C, Mercado Pago, garantías, envíos y cancelaciones
# =============================================================================

CASOS_PRUEBA_ML = [
    # Peticiones — solicitudes de información
    {
        'texto'   : '¿Cuánto tiempo tengo para devolver un producto nuevo que compré?',
        'esperado': 'Petición',
        'tema'    : 'Devoluciones'
    },
    {
        'texto'   : '¿Cómo funciona el programa de Compra Protegida de Mercado Libre?',
        'esperado': 'Petición',
        'tema'    : 'Compra Protegida'
    },
    {
        'texto'   : '¿En cuánto tiempo me acreditan el reembolso si pagué con tarjeta de crédito?',
        'esperado': 'Petición',
        'tema'    : 'Reembolsos'
    },
    {
        'texto'   : '¿Qué productos están excluidos del programa de devoluciones?',
        'esperado': 'Petición',
        'tema'    : 'Políticas de devolución'
    },
    # Quejas — insatisfacción con el servicio
    {
        'texto'   : 'El proceso de devolución es demasiado complicado y lento',
        'esperado': 'Queja',
        'tema'    : 'Devoluciones'
    },
    {
        'texto'   : 'Estoy muy insatisfecho con la atención del servicio de Mercado Libre',
        'esperado': 'Queja',
        'tema'    : 'Atención al cliente'
    },
    # Reclamos — exigencia formal
    {
        'texto'   : 'Recibí un producto diferente al que compré y exijo la devolución de mi dinero',
        'esperado': 'Reclamo',
        'tema'    : 'Compra Protegida'
    },
    {
        'texto'   : 'No recibí mi pedido y ya pasaron 30 días, reclamo el reembolso completo',
        'esperado': 'Reclamo',
        'tema'    : 'Envíos'
    },
    # Sugerencias — propuestas
    {
        'texto'   : 'Propongo que el proceso de devolución sea completamente digital sin etiqueta física',
        'esperado': 'Sugerencia',
        'tema'    : 'Devoluciones'
    },
    # Caso fuera del alcance documental
    {
        'texto'   : '¿Cuál es el precio del dólar hoy en Colombia?',
        'esperado': 'Petición',
        'tema'    : 'Fuera de alcance — debe retornar fallback'
    },
]

print('🧪 CASOS DE PRUEBA — Sistema PQRS Mercado Libre')
print('=' * 65)

correctos = 0
for i, caso in enumerate(CASOS_PRUEBA_ML, 1):
    resultado = procesar_pqrs(caso['texto'], usuario='tester', chat_id='test')
    correcto  = resultado['tipo_pqrs'] == caso['esperado']
    correctos += int(correcto)
    estado    = '✅' if correcto else '❌'

    print(f'\n{estado} Caso {i} [{caso["tema"]}]')
    print(f'   Consulta  : {caso["texto"][:65]}...')
    print(f'   Esperado  : {caso["esperado"]}')
    print(f'   Detectado : {resultado["tipo_pqrs"]} (confianza: {resultado["confianza"]:.0%})')
    print(f'   Fuente    : {resultado["fuente_doc"]}')
    print(f'   Página(s) : {resultado["pagina_fuente"]}')
    print(f'   Respuesta : {resultado["respuesta"][:150]}...')

print(f'\n{"="*65}')
print(f'📊 Resultado final: {correctos}/{len(CASOS_PRUEBA_ML)} casos correctos '
      f'({correctos/len(CASOS_PRUEBA_ML)*100:.0f}% de exactitud)')

"""## 📊 Paso 11 — Visualización de registros SQLite"""

# =============================================================================
# PASO 11: Visualizar los registros almacenados en SQLite
# Útil para revisar el historial de consultas procesadas y las fuentes usadas
# =============================================================================
import pandas as pd

# Cargar todos los registros de la base de datos
df_logs = pd.read_sql_query(
    'SELECT id, fecha, usuario, tipo_pqrs, documento_fuente, pagina_fuente, '
    'score_similitud, pregunta FROM pqrs_logs ORDER BY id DESC LIMIT 20',
    db_conn
)

print(f'📋 Últimos {len(df_logs)} registros PQRS en SQLite:')
print('=' * 70)
if df_logs.empty:
    print('   No hay registros aún. Ejecuta el Paso 10 primero.')
else:
    # Acortar la pregunta para visualización
    df_logs['pregunta_corta'] = df_logs['pregunta'].str[:60] + '...'
    display(df_logs[['id', 'fecha', 'tipo_pqrs', 'documento_fuente', 'pagina_fuente', 'pregunta_corta']])

    # Estadísticas generales
    print('\n📊 Distribución por tipo PQRS:')
    print(df_logs['tipo_pqrs'].value_counts().to_string())

    print('\n📄 Documentos más consultados:')
    print(df_logs['documento_fuente'].value_counts().head(5).to_string())